version: 2

sources:
  - name: NETFLIX
    database: NETFILX_DB
    schema: NETFILX_SCH
    tables:
    - name: s_GENOME_TAGS
      identifier: RAW_GENOME_TAGS
    - name: s_MOVIE_RATINGS
      identifier: MOVIE_RATINGS
    - name: s_MOVIE
      identifier: RAW_MOVIES
    - name: s_LINKS
      identifier: RAW_LINKS
    - name: s_TAGS
      identifier: RAW_TAGS
    - name: s_Microsoft_Users
      identifier: MICROSOFT_USERS